	  CSEG AT 00H
	  MOV DPTR,#0FFFFH
	  MOV R0,DPL
	  MOV R1,DPH
	  MOV DPTR,#0FFFFH
	  MOV R2,DPL
	  MOV R3,DPH
	  MOV A,R2
	  ADD A,R0
	  MOV 32H,A
	  MOV A,R3
	  JNZ LOOP
	  MOV A,R1
	  JZ GO
LOOP: ADDC A,R1
	  MOV 31H,A
GO:	  JNC NEXT
	  INC 30H
NEXT: NOP
	  END